# -*- coding: utf-8 -*-
"""
/***************************************************************************
 BuildingDetector
                                 A QGIS plugin
 Applys the mask r-cnn algorithm to detect and segment buildings.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-01-31
        copyright            : (C) 2022 by André Estevam Costa Oliveira
        email                : andre.estevam.unb@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load BuildingDetector class from file BuildingDetector.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .building_detector import BuildingDetector
    return BuildingDetector(iface)
